name: Deploy to server

on:
  registry_package:
    types: [published, updated]

  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:

      # Sends a POST request to my server, telling it to restart. On restart, it will pull the latest docker image
      - name: Call server endpoint
        run: |
          curl ${{ secrets.SERVER_ENDPOINT }}/power \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.PANEL_KEY }}' \
            -X POST \
            -b 'pterodactyl_session'='eyJpdiI6InhIVXp5ZE43WlMxUU1NQ1pyNWRFa1E9PSIsInZhbHVlIjoiQTNpcE9JV3FlcmZ6Ym9vS0dBTmxXMGtST2xyTFJvVEM5NWVWbVFJSnV6S1dwcTVGWHBhZzdjMHpkN0RNdDVkQiIsIm1hYyI6IjAxYTI5NDY1OWMzNDJlZWU2OTc3ZDYxYzIyMzlhZTFiYWY1ZjgwMjAwZjY3MDU4ZDYwMzhjOTRmYjMzNDliN2YifQ%3D%3D' \
            -d '{ "signal": "restart"}'